### ISSUE TITLE
cmp: proxy_bunny: No such file or directory

### ISSUE THREAD

**Issue by Wizzard033** [UCLA-CS130/Team05#40]
The integration test for the reverse proxy handler that was made for us isn't working right
To replicate, just run "make test" in the master branch

**Comment by Wizzard033** [comment]
Found the issue was with a race condition in the integration test. Jordan said he fixed it, but hasn't gotten around to a pull request for it.

**Comment by gotitmemorize** [comment]
Fix will be introduced in a pull request along with other changes
